export const GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILURE = 'GET_LOGIN_FAILURE';

// export const ADD_LOGIN_REQUEST = 'ADD_LOGIN_REQUEST';
// export const ADD_LOGIN_SUCCESS = 'ADD_LOGIN_SUCCESS';
// export const ADD_LOGIN_FAILURE = 'ADD_LOGIN_FAILURE';

// export const DELETE_LOGIN_REQUEST = 'DELETE_LOGIN_REQUEST';
// export const DELETE_LOGIN_SUCCESS = 'DELETE_LOGIN_SUCCESS';
// export const DELETE_LOGIN_FAILURE = 'DELETE_LOGIN_FAILURE';

